server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url:  jdbc:mysql://localhost:3306/heima
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:  #改成以ip地址注册到服务中心
    prefer-ip-address: true
    ip-address: 127.0.0.1
zuul:
  prefix: /api # 添加路由前缀
  routes:
    item-service: /item/** # 将商品微服务映射到/item/**
mybatis:
  mapper-locations: mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.leyou.item.entity

mapper:
  wrap-keyword: "`{0}`"